app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
       
home:
    path: /
    controller: App\Controller\HomeController::home

home2:
    path: /home2
    controller: App\Controller\HomeController::home2
home3:
    path: /home3
    controller: App\Controller\HomeController::home3   

logout:
    path: /logout
